name: publish-resume
on:
  push:
    branches:
      - master

jobs:
  build-resume-pdf:
    name: build-resume-pdf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dante-ev/latex-action@latest
        with:
          root_file: resume.tex
      - uses: actions/upload-artifact@v3
        with:
          name: resume
          path: resume.pdf
      - id: date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y-%m-%d %H:%M:%S")"
      - uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.date.outputs.date }}
          files: resume.pdf
