name: publish-resume
on:
  push:
    branches:
      - master

jobs:
  build-resume-pdf:
    name: build-resume-pdf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dante-ev/latex-action@latest
        with:
          root_file: resume.tex
      - uses: actions/upload-artifact@v3
        with:
          name: resume
          path: resume.pdf
      - id: date
        run: |
          sudo apt-get update
          sudo apt-get install -y tzdata
          echo "::set-output name=date::$(date -u "+%Y-%m-%dT%H:%M:%S")"
        env:
          TZ: Australia/Melbourne
          DEBIAN_FRONTEND: noninteractive
      - run: |
          gh release delete -y latest
          git tag --delete latest || true
          git tag latest
      - uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.date.outputs.date }}
          tag_name: latest
          files: resume.pdf
